apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-k8s.yaml -v convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  type: NodePort
  ports:
    - nodePort: 32323
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: nginx
