apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: prodtasksproj
  name: prodtasksproj
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: prodtasksproj
