apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: static-data
  name: static-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
